name: Deploy Strapi on VPS

on:
  push:
    branches: [main]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: ssh into the VPS and deploy Strapi with Docker
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: |
            cd anime-reviews/backend
            git pull
            docker-compose down
            docker-compose up -d
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          privateKey: ${{ secrets.PRIVATE_KEY }}
